# Encountered Issues and Errors

```bash
Task boosts.tasks.send_inspirational_to_self[1a86aa2f-5735-4f25-a8c6-f70d7a5ef822] raised unexpected: FieldError("Cannot resolve keyword 'user_id' into field. Choices are: author, author_id, body, created, id, inspirationalsent")
```